version: 0.2

phases:
    pre_build:
        commands:
            - echo Logging in to Amazon ECR...
            - aws ecr-public get-login-password --region us-east-1 | docker login --username AWS --password-stdin public.ecr.aws/q7c2w2w2
            - REPOSITORY_URI=public.ecr.aws/q7c2w2w2/demoapp-backend
            - COMMIT_HASH=$(echo $CODEBUILD_RESOLVED_SOURCE_VERSION | cut -c 1-7)
            - IMAGE_TAG=${COMMIT_HASH:=latest}
    build:
        commands:
            - echo Build started on `date`
            - echo Building the Docker image $REPOSITORY_URI:latest
            - docker build -t $REPOSITORY_URI:latest .
            - docker tag $REPOSITORY_URI:latest $REPOSITORY_URI:$IMAGE_TAG
    post_build:
        commands:
            - echo Build completed on `date`
            - echo Pushing the Docker images...
            - docker push $REPOSITORY_URI:latest
            - docker push $REPOSITORY_URI:$IMAGE_TAG
            - echo printf '{"imageURI":"'$REPOSITORY_URI':latest"}' > imageDetail.json
            - cat imageDetail.json

artifacts:
    files:
        - taskdef.json
        - appspec.yaml
        - imageDetail.json
